"""baseline

Revision ID: 7e1367b61cd1
Revises: 
Create Date: 2026-01-21 16:21:09.285795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1367b61cd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dobs_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('branch_city', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('business_ids',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iqaama_number', sa.String(length=20), nullable=False),
    sa.Column('iqaama_expiry', sa.Date(), nullable=True),
    sa.Column('saudi_driving_license', sa.Boolean(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('absher_number', sa.String(length=15), nullable=True),
    sa.Column('previous_sponsor_number', sa.String(length=50), nullable=True),
    sa.Column('iqama_card_upload', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('car_details', sa.String(length=200), nullable=True),
    sa.Column('assignment_date', sa.Date(), nullable=True),
    sa.Column('onboarding_stage', sa.String(length=50), nullable=False),
    sa.Column('qiwa_contract_created', sa.Boolean(), nullable=True),
    sa.Column('company_contract_created', sa.Boolean(), nullable=True),
    sa.Column('qiwa_transfer_approved', sa.Boolean(), nullable=True),
    sa.Column('sponsorship_transfer_done', sa.Boolean(), nullable=True),
    sa.Column('qiwa_contract_status', sa.String(length=20), nullable=True),
    sa.Column('sponsorship_transfer_status', sa.String(length=20), nullable=True),
    sa.Column('ops_manager_approved_at', sa.DateTime(), nullable=True),
    sa.Column('hr_approved_at', sa.DateTime(), nullable=True),
    sa.Column('ops_supervisor_approved_at', sa.DateTime(), nullable=True),
    sa.Column('fleet_manager_approved_at', sa.DateTime(), nullable=True),
    sa.Column('finance_approved_at', sa.DateTime(), nullable=True),
    sa.Column('ops_manager_approved', sa.Boolean(), nullable=True),
    sa.Column('hr_approved_by', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.String(length=50), nullable=True),
    sa.Column('mobile_issued', sa.Boolean(), nullable=True),
    sa.Column('tamm_authorized', sa.Boolean(), nullable=True),
    sa.Column('transfer_fee_paid', sa.Boolean(), nullable=True),
    sa.Column('transfer_fee_amount', sa.Float(), nullable=True),
    sa.Column('transfer_fee_paid_at', sa.DateTime(), nullable=True),
    sa.Column('transfer_fee_receipt', sa.String(length=200), nullable=True),
    sa.Column('issued_mobile_number', sa.String(length=20), nullable=True),
    sa.Column('issued_device_id', sa.String(length=100), nullable=True),
    sa.Column('tamm_authorization_ss', sa.String(length=200), nullable=True),
    sa.Column('sponsorship_transfer_proof', sa.String(length=200), nullable=True),
    sa.Column('driver_type_id', sa.Integer(), nullable=False),
    sa.Column('company_contract_file', sa.String(length=200), nullable=True),
    sa.Column('promissory_note_file', sa.String(length=200), nullable=True),
    sa.Column('qiwa_contract_file', sa.String(length=200), nullable=True),
    sa.Column('sponsorship_transfer_completed_at', sa.DateTime(), nullable=True),
    sa.Column('offboarding_stage', sa.String(length=50), nullable=True),
    sa.Column('offboarding_reason', sa.Text(), nullable=True),
    sa.Column('offboarding_requested_at', sa.DateTime(), nullable=True),
    sa.Column('offboard_request', sa.Boolean(), nullable=True),
    sa.Column('offboard_requested_by', sa.String(length=100), nullable=True),
    sa.Column('offboard_reason', sa.String(length=255), nullable=True),
    sa.Column('offboard_requested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hr_approved_by'], ['dobs_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id'),
    sa.UniqueConstraint('iqaama_number')
    )
    op.create_table('business_driver',
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_ids.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('business_id', 'driver_id')
    )
    op.create_table('driver_business_ids',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('business_id_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_driver_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id_id'], ['business_ids.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ops_supervisor_cleared', sa.Boolean(), nullable=True),
    sa.Column('ops_supervisor_cleared_at', sa.DateTime(), nullable=True),
    sa.Column('ops_supervisor_note', sa.Text(), nullable=True),
    sa.Column('fleet_cleared', sa.Boolean(), nullable=True),
    sa.Column('fleet_cleared_at', sa.DateTime(), nullable=True),
    sa.Column('fleet_damage_report', sa.Text(), nullable=True),
    sa.Column('fleet_damage_cost', sa.Float(), nullable=True),
    sa.Column('finance_cleared', sa.Boolean(), nullable=True),
    sa.Column('finance_cleared_at', sa.DateTime(), nullable=True),
    sa.Column('finance_invoice_file', sa.String(length=200), nullable=True),
    sa.Column('finance_adjustments', sa.Float(), nullable=True),
    sa.Column('finance_note', sa.Text(), nullable=True),
    sa.Column('hr_cleared', sa.Boolean(), nullable=True),
    sa.Column('hr_cleared_at', sa.DateTime(), nullable=True),
    sa.Column('hr_note', sa.Text(), nullable=True),
    sa.Column('tamm_revoked', sa.Boolean(), nullable=True),
    sa.Column('tamm_revoked_at', sa.DateTime(), nullable=True),
    sa.Column('company_contract_cancelled', sa.Boolean(), nullable=True),
    sa.Column('qiwa_contract_cancelled', sa.Boolean(), nullable=True),
    sa.Column('salary_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['dobs_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offboarding')
    op.drop_table('driver_business_ids')
    op.drop_table('business_driver')
    op.drop_table('drivers')
    op.drop_table('business_ids')
    op.drop_table('dobs_user')
    op.drop_table('businesses')
    # ### end Alembic commands ###
